branches:
  only:
  - dev
language: python
cache: yarn

# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
  - pip install docker

# command to run tests
script:
  - echo $TRAVIS_COMMIT
  - docker login --username=hesam80 --password=sa13801380
  - docker build -t  flaskapp:$TRAVIS_COMMIT .
  #- docker tag flaskapp:$TRAVIS_COMMIT hesam80/flaskapp:latest
  #- docker image ls
  #- docker push hesam80/flaskapp:latest
  - COLLECT_ERROR=True fandogh login --username hesam80 --password sa13801380
  #- COLLECT_ERROR=TRUE fandogh image publish --version $TRAVIS_COMMIT
  - fandogh service apply -f flaskapp.yml